# Builds the logos-chat-module library
{ pkgs, common, src, logosWakuModule, logosSdk }:

pkgs.stdenv.mkDerivation {
  pname = "${common.pname}-lib";
  version = common.version;
  
  inherit src;
  inherit (common) buildInputs cmakeFlags meta env;
  
  # Add logosSdk to nativeBuildInputs for logos-cpp-generator
  nativeBuildInputs = common.nativeBuildInputs ++ [ logosSdk ];
  
  preConfigure = ''
    runHook prePreConfigure
    
    # Create some_folder directory for generated files
    mkdir -p ./some_folder
    
    # Copy include files from logos-waku-module result
    echo "Copying include files from logos-waku-module..."
    if [ -d "${logosWakuModule}/include" ]; then
      echo "Found include directory in logos-waku-module"
      cp -r "${logosWakuModule}/include"/* ./some_folder/
      echo "Copied include files:"
      ls -la ./some_folder/
    else
      echo "Warning: No include directory found in logos-waku-module"
    fi
    
    # Run logos-cpp-generator with metadata.json and --general-only flag
    echo "Running logos-cpp-generator..."
    logos-cpp-generator --metadata ${src}/metadata.json --general-only --output-dir ./some_folder
    
    # Check what was generated by logos-cpp-generator
    echo "Checking generated files in some_folder:"
    ls -la ./some_folder/
    
    # Create include directory and move generated files there if they exist
    if [ -f "./some_folder/core_manager_api.h" ] || [ -f "./some_folder/logos_sdk.h" ]; then
      echo "Creating include directory and moving generated files..."
      mkdir -p ./some_folder/include
      # Move generated header files to include directory
      for file in ./some_folder/*.h; do
        if [ -f "$file" ]; then
          mv "$file" ./some_folder/include/
        fi
      done
      # Also copy generated .cpp files to include directory
      for file in ./some_folder/*.cpp; do
        if [ -f "$file" ]; then
          cp "$file" ./some_folder/include/
        fi
      done
      echo "Generated include directory:"
      ls -la ./some_folder/include/
    else
      echo "Warning: No header files generated by logos-cpp-generator"
    fi
    
    runHook postPreConfigure
  '';
  
  installPhase = ''
    runHook preInstall
    
    mkdir -p $out/lib
    # Find and copy the built library file from the modules directory
    if [ -f modules/chat_plugin.dylib ]; then
      cp modules/chat_plugin.dylib $out/lib/
    elif [ -f modules/chat_plugin.so ]; then
      cp modules/chat_plugin.so $out/lib/
    else
      echo "Error: No library file found"
      exit 1
    fi
    
    # Also install the generated include files
    if [ -d "./some_folder/include" ]; then
      mkdir -p $out/include
      cp -r ./some_folder/include/* $out/include/
      echo "Installed generated include files:"
      ls -la $out/include/
    fi
    
    runHook postInstall
  '';
}

